### ISSUE TITLE
Plugin not showing up in the Plugin Manager

### ISSUE THREAD

**Issue by endless-devourer** [w4ffl35/krita_stable_diffusion#22]
**Describe the bug**
Copied all files to correct directories, even went as far as to removing the "2.0" in the plugin folder and moving the contents that inside the PLUGIN up a directory level. When I go to the Plugin Manager, the plugin doesn't appear. I use a Krita AppImage, 5.0 (my main one) and tried on the latest 5.1.1

**Expected behavior**
See the plugin be listed in the Python Plugin Manager window

**Desktop (please complete the following information):**
OS: Kubuntu 20.04.5 LTS

**Comment by w4ffl35** [comment]
@endless-devourer - thank you for your report!

Please post a screenshot of your directory structure. mine looks like this:

```
/home/$USER/.local/share/krita/pykrita/krita_stable_diffusion
/home/$USER/local/share/krita/pykrita/Krita Stable Diffusion Plugin
```
or instead you may see:

```
/home/$USER/.local/share/krita/pykrita/krita_stable_diffusion
/home/$USER/.local/share/krita/pykrita/krita_stable_diffusion.desktop
```
where `$USER` is your username.

Additionally I am using an older version of Krita so I will upgrade and ensure that this plugin works with the latest version.

If your directory structure is correctly, my recommendation to you at this time would be to wait for v0.3.0. 

If you would like to be  adventurous you could try this plugin with Krita 4.2.9.

In the meantime, keep on eye on [this discussion thread for information about v0.3.0](https://github.com/w4ffl35/krita_stable_diffusion/discussions/24)

**Comment by w4ffl35** [comment]
@endless-devourer also feel free to join my discord server for faster updates https://discord.gg/PUVDDCJ7gz

**Comment by w4ffl35** [comment]
@endless-devourer you might want to try installing again. Version 0.2.2-alpha fixes a number of installation issues. thanks again for your report.
