### ISSUE TITLE
403 on running install instructions

### ISSUE THREAD

**Issue by wrac4242** [w4ffl35/krita_stable_diffusion#37]
**Describe the bug**
amazon returns 403 when running `wget https://sddist.s3.amazonaws.com/krita-stable-diffusion_multifile-0.2.1.tar`

**To Reproduce**

run `wget https://sddist.s3.amazonaws.com/krita-stable-diffusion_multifile-0.2.1.tar`

**Expected behavior**
successful download

**Screenshots**
![image](https://user-images.githubusercontent.com/42539664/192151732-e1e31770-187e-432f-b173-cdf41dfe8c36.png)

**Desktop (please complete the following information):**

- OS: arch linux

**Comment by w4ffl35** [comment]
Thank you @wrac4242 this has been resolved

**Comment by wrac4242** [comment]
can confirm it is resolved, thanks for the quick response
