### ISSUE TITLE
Plugin unable to load

### ISSUE THREAD

**Issue by wrac4242** [w4ffl35/krita_stable_diffusion#38]
**Describe the bug**
Plugin unable to load due to issues loading module "torch"

**To Reproduce**
Install plugin using plugin script
load plugin on the krita configure page
see console for error

**Expected behavior**
plugin starting correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/42539664/192153426-84c35324-0c3a-4a69-9ae8-bd0c0fc70ff0.png)

**Desktop (please complete the following information):**

- OS: Arch Linux 

**Additional context**
On latest build 0.2.1

**Comment by w4ffl35** [comment]
![image](https://user-images.githubusercontent.com/25737761/192155945-b8d704ff-9169-4a86-97cb-526088529312.png)

Hi @wrac4242 it looks like you're attempting to run this on a macbook, is that correct? 

Unfortunately the compiled version of this plugin only has linux support.

**Comment by wrac4242** [comment]
@w4ffl35, i am not running this on a mac, i am running it on an x86_64 based machine

**Comment by w4ffl35** [comment]
@wrac4242 Thanks you are the second person to report this so it must be a legitimate issue -- i'm looking into it now.

**Comment by w4ffl35** [comment]
I have located the issue along with another and am working on a patch - thank you for the report @wrac4242

**Comment by w4ffl35** [comment]
@wrac4242 this (and all other) installation issues should now be resolved with release 0.2.2-alpha

thanks again for your reports, very helpful.
