### ISSUE TITLE
0.3.1's release notes have a bad repo link

### ISSUE THREAD

**Issue by Jellybit** [w4ffl35/krita_stable_diffusion#48]
In the [0.3.1](https://github.com/w4ffl35/krita_stable_diffusion/releases/tag/0.3.1) release, there is a link that says, "[sdrunner is compiled from this repo](https://github.com/w4ffl35/stable-diffusion/tree/feature/windows-support)". This gets a 404 error when clicked on.

**Comment by w4ffl35** [comment]
Thanks fixed
