### ISSUE TITLE
Negative prompting.

### ISSUE THREAD

**Issue by DarkAlchy** [w4ffl35/krita_stable_diffusion#53]
It needs to be added as it makes far too drastic of a change (for the better) to not have it.  I don't care how many of these Krita plugins are made, or how great they are, for without the negative prompting that Automatic1111 web-gui has they are worthless to me (and a lot of people in the know).

**Comment by w4ffl35** [comment]
> It needs to be added as it makes far too drastic of a change (for the better) to not have it.  I don't care how many of these Krita plugins are made, or how great they are, for without the negative prompting that Automatic1111 web-gui has they are worthless to me (and a lot of people in the know).

Good feedback thank you

**Comment by Jellybit** [comment]
Strong agreement here. Negative prompting has become almost as important as the prompting itself. Prompting lets you ask for things, and negative prompting lets you control the results of that request. AUTOMATIC1111 is really defining workflows more than anyone else.

**Comment by w4ffl35** [comment]
It has been added for the next release.

**Comment by DarkAlchy** [comment]
> It has been added for the next release.

Majorly sweet.

Thank you for your fast work. :)
