### ISSUE TITLE
Refuses to use the sampler I set.

### ISSUE THREAD

**Issue by DarkAlchy** [w4ffl35/krita_stable_diffusion#59]
Windows 10 and I have it set to use euler_a for imgtoimg and whatever the second one is for BUT when I do txt2img I can't set the sampler?  Seems to default to PLMS (I have the box unchecked as I despise PLMS) so I am not sure what is going on.

**Comment by w4ffl35** [comment]
> Windows 10 and I have it set to use euler_a for imgtoimg and whatever the second one is for BUT when I do txt2img I can't set the sampler?  Seems to default to PLMS (I have the box unchecked as I despise PLMS) so I am not sure what is going on.

Thanks I'll look into this.
